export const FETCH_IMAGE_LIST_LOADING = "FETCH_IMAGE_LIST_LOADING";
export const FETCH_IMAGE_LIST_SUCCESS = "FETCH_IMAGE_LIST_SUCCESS";
export const FETCH_IMAGE_LIST_FAILURE = "FETCH_IMAGE_LIST_FAILURE";

export const ADD_NEW_IMAGE = "ADD_NEW_IMAGE";
